// Generated by CoffeeScript 1.3.3
(function() {

  this.NumberHelpers = (function() {

    function NumberHelpers() {}

    NumberHelpers.number_to_currency = function(float, opts) {
      var decimal, integer, number, _delimiter, _precision, _ref, _ref1, _ref2, _ref3, _ref4, _separator, _unit;
      if (opts == null) {
        opts = {};
      }
      _precision = (_ref = opts.precision) != null ? _ref : 2;
      _unit = (_ref1 = opts.unit) != null ? _ref1 : '$';
      _separator = (_ref2 = opts.separator) != null ? _ref2 : '.';
      _delimiter = (_ref3 = opts.delimiter) != null ? _ref3 : ',';
      number = float.toString().split('.');
      integer = number[0];
      decimal = number[1];
      decimal = parseFloat("0." + decimal).toFixed(_precision);
      decimal = decimal.toString().split('.');
      decimal = (_ref4 = decimal[1]) != null ? _ref4 : '';
      if (!decimal) {
        _separator = '';
      }
      if (isNaN(integer)) {
        _separator = decimal = '';
      }
      integer = NumberHelpers.number_with_delimiter(integer, {
        delimiter: _delimiter
      });
      return "" + _unit + integer + _separator + decimal;
    };

    NumberHelpers.number_with_delimiter = function(float, opts) {
      var decimal, integer, number, rgx, _delimiter, _ref, _ref1, _ref2, _separator;
      if (opts == null) {
        opts = {};
      }
      _separator = (_ref = opts.separator) != null ? _ref : '.';
      _delimiter = (_ref1 = opts.delimiter) != null ? _ref1 : ',';
      number = float.toString().split(".");
      integer = number[0];
      decimal = (_ref2 = number[1]) != null ? _ref2 : '';
      if (!decimal) {
        _separator = '';
      }
      rgx = /(\d+)(\d{3})/;
      if (_delimiter) {
        while (rgx.test(integer)) {
          integer = integer.replace(rgx, "$1" + _delimiter + "$2");
        }
      }
      return "" + integer + _separator + decimal;
    };

    return NumberHelpers;

  })();

}).call(this);
