// Generated by CoffeeScript 1.3.3
(function() {

  this.NumberHelpers = (function() {

    function NumberHelpers() {}

    NumberHelpers.number_to_currency = function(float, opts) {
      var decimal, integer, _delimiter, _locale, _precision, _ref, _ref1, _ref2, _ref3, _ref4, _separator, _unit;
      if (opts == null) {
        opts = {};
      }
      _locale = (_ref = opts.locale) != null ? _ref : 'en';
      _precision = (_ref1 = opts.precision) != null ? _ref1 : 2;
      _unit = (_ref2 = opts.unit) != null ? _ref2 : '$';
      _separator = (_ref3 = opts.separator) != null ? _ref3 : '.';
      _delimiter = (_ref4 = opts.delimiter) != null ? _ref4 : ',';
      if (typeof float === 'string') {
        float = parseFloat(float, 10);
      }
      if (typeof float !== 'number') {
        return Number.NaN;
      }
      integer = parseInt(float);
      if (_precision === 0) {
        _separator = '';
      }
      _precision = _precision + 2;
      decimal = (float - integer).toString();
      decimal = decimal.substring(2, _precision);
      return "" + _unit + integer + _separator + decimal;
    };

    return NumberHelpers;

  })();

}).call(this);
